version: '3'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

volumes:
  postgres_volume:
